paths:
  '/login':
    post:
      tags:
        - login
      summary: login
      description: login
      deprecated: false
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - reqData
            properties:
              reqData:
                type: object
                required:
                  - searchFilter
                properties:
                  id:
                    description: '玩家帳號'
                    type: string
                    default: 'null'
                    example: 'kkgod'
                  password:
                    description: '玩家密碼'
                    type: string
                    default: '7c4a8d09ca3762af61e59520943dc26494f8941b'
                    example: '7c4a8d09ca3762af61e59520943dc26494f8941b'
      responses:
        '200':
          description: OK
          schema:
            required:
              - status
              - result
            properties:
              status:
                type: integer
                format: int32 
                enum:
                  - 1
                  - 8001
                default: 1
                example: 1
              result:
                properties:
                    token:
                      type: string
                      example: '7c4a8d09ca3762af61e59520943dc26494f8941b'
                      default: 'null'
